//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
public class GameUtils{
	public static void playSound(AudioClip clip,AudioSource audioPlayer){
		audioPlayer.Stop ();
		audioPlayer.clip = clip;
		audioPlayer.loop = false;
		audioPlayer.time = 0;
		audioPlayer.Play ();
	}
}

