//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public enum FighterStates{
	IDLE,WALK,WALK_BACK,JUMP,DUCK,
	HADOKEN,ATTACK,TAKE_HIT,TAKE_HIT_DEFEND,
	DEFEND,CELEBRATE,DEAD,NONE
}

